### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Kartvya69** [MovTery/ZalithLauncher#164]
### Issue Type / 问题类型

Application Issue / 应用问题

### Issue Description / 问题描述

When I minimize my screen and after I open it I get black screen but the thing is the minecraft is still functional I've get a lot of works to do while keeping my game enabled so please help me. I think this is happening after the latest update 

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17274961/latestlog.txt)

### Android Version / Android 版本

10

### App Version / 应用版本

1.3.3

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

Realme 5i, Android 10, arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by agent1243** [comment]
I have the same problem, I don't understand why the launcher creator doesn't want to solve this bug
