### ISSUE TITLE
ERROR Install forge version 1.12.2 

### ISSUE THREAD

**Issue by MARCOS30864** [MovTery/ZalithLauncher#179]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

When I go to install 1.12.2 forge it simply exits with error 1

### Log File / 日志文件

...

### Screenshots or Videos / 截图或视频

...

### Reproduction Steps / 复现步骤

```markdown
...
```

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.5.1

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

Arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by suq-weer** [comment]
No log file?🙃

**Comment by ThatOneSheep** [comment]
Maybe try  internal 8 instead of internal 17 or 21

**Comment by MARCOS30864** [comment]
It has been fixed now, just clear the app cache and update
