### ISSUE TITLE
Isuue 1.20.1 and 1.21.2 launcher version latest 1.3.6 

### ISSUE THREAD

**Issue by Otatsuki** [MovTery/ZalithLauncher#189]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

So i open the game and launched 1.20.1 and it crash for some reason which i dont khow 
So i tried latest version 1.21.2 it said it didn't support

### Log File / 日志文件

1.20.1 log file 

--------- Start launching the game
Info: Launcher version: 1.3.6 (9941143)
Info: Architecture: arm64
Info: Device model: OnePlus ONEPLUS A6010
Info: API version: 30
Info: Selected Minecraft version: 1.20.1
Info: Custom Java arguments: NONE
Info: Java Runtime: Internal-17
Info: Account: Otatsuki (Local)
--------- beginning of perf

--------- beginning of system

--------- beginning of main

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.zh/cache
Added custom env: AWTSTUB_WIDTH=1124
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_BIG_CORE_AFFINITY=1
Added custom env: POJAV_NATIVEDIR=/data/app/~~Ak0ku70blseLPvvtWPOCeg==/net.kdt.pojavlaunch.zh-cbafOwiBAB5_PRWRkyjQig==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.zh/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.zh/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LIBGL_VGPU_DUMP=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~Ak0ku70blseLPvvtWPOCeg==/net.kdt.pojavlaunch.zh-cbafOwiBAB5_PRWRkyjQig==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=800
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
Dump the content of VGPU shader conversion
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  ( 4195): dlopen libgl4es_114.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjli.so success
I/jrelog  ( 4195): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libverify.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjava.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnet.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnio.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjdwp.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnet.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libprefs.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libverify.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjli.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/librmi.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libdt_socket.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libzip.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnio.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjava.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libextnet.so success

I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmlib_image.so success
I/jrelog  ( 4195): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  ( 4195): dlopen /data/app/~~Ak0ku70blseLPvvtWPOCeg==/net.kdt.pojavlaunch.zh-cbafOwiBAB5_PRWRkyjQig==/lib/arm64/libopenal.so success

I/jrelog  ( 4195): Done processing args

I/jrelog  ( 4195): Found JLI lib
I/jrelog  ( 4195): Calling JLI_Launch

Error: Could not find or load main class net.minecraft.client.main.Main
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.main.Main

### Screenshots or Videos / 截图或视频

https://github.com/user-attachments/assets/876e3a13-bc09-4a10-a6d0-55c63f86a052

### Android Version / Android 版本

11

### App Version / 应用版本

1.3.6

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

Oneplus 6T android 11 

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by FnXez** [comment]
Im also experiencing this issue. Do you already have the solution? Let me know.
