### ISSUE TITLE
Mods/resource packs preview image

### ISSUE THREAD

**Issue by MARCOS30864** [MovTery/ZalithLauncher#191]
### Feature Description / 功能描述

A small mod image selection screen just like the curseforge website itself 
![2024102217085775](https://github.com/user-attachments/assets/4fadfc3c-3ef1-46e2-8488-5efc2ad7b31f)

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by Dorian12192** [comment]
That's a good idea, I hope they put it in 🙏

**Comment by MARCOS30864** [comment]
Thank you very much

**Comment by Dorian12192** [comment]
but it doesn't appear to me
