### ISSUE TITLE
Interface configuration

### ISSUE THREAD

**Issue by Dorian12192** [MovTery/ZalithLauncher#193]
### Feature Description / 功能描述

Hi, for some update of the launcher, could you put a new design on the configuration part while you play, it is already old and a new design should be put on it? 

### Additional Information / 其他信息

![Screenshot_20241022_213942_Zalith Launcher](https://github.com/user-attachments/assets/47791f10-ad23-4d34-86e4-76a79e7e6f7a)

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
How about this?

https://github.com/user-attachments/assets/c9eedbeb-4e3a-4010-9d6e-12bd5ad0cddc

**Comment by MovTery** [comment]
How about this?

https://github.com/user-attachments/assets/c9eedbeb-4e3a-4010-9d6e-12bd5ad0cddc

**Comment by Dorian12192** [comment]
Yes, that add pls!!
