### ISSUE TITLE
the most annoying bug 

### ISSUE THREAD

**Issue by Dorian12192** [MovTery/ZalithLauncher#194]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

When I click on it many times and the game crashes, the controls get stuck, I don't know if it's my device or the game, because in the original pojavlauncher they fixed it, and here they don't. 

### Log File / 日志文件

No log

### Screenshots or Videos / 截图或视频

https://github.com/user-attachments/assets/6b720cb1-18a3-4dc1-8582-cfec278b6d10

### Reproduction Steps / 复现步骤

```markdown
1 sting him many times
2 controls get stuck within seconds
```

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.6

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

Galaxy tap A9+

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Dorian12192** [comment]
Yeah 😠

**Comment by S0SUKEAIZEN** [comment]
@MovTery  Please solve this persistent issue that we have encountered countless times. the users are getting annoyed quite frequently because of this issue. i would suggest you to find the root of the cause of this issue. thanks.

**Comment by S0SUKEAIZEN** [comment]
@MovTery come on brotha, this bug is annoying as hell, atleast keep us updated about it, hold up lemme translate it for ya
來吧，兄弟，這個錯誤真是煩人，至少讓我們了解最新情況，

**Comment by S0SUKEAIZEN** [comment]
@MovTery come on brotha, this bug is annoying as hell, atleast keep us updated about it, hold up lemme translate it for ya
來吧，兄弟，這個錯誤真是煩人，至少讓我們了解最新情況，

**Comment by S0SUKEAIZEN** [comment]
@MovTery pls fix it 😭

**Comment by Dorian12192** [comment]
Pls!! 😔

**Comment by S0SUKEAIZEN** [comment]
@MovTery wdym? it's literally just clicking and using 3 other fingers (in my case.) while playing any version of Minecraft (1.8.8 for example)
