### ISSUE TITLE
When will the app be released in official stores? 

### ISSUE THREAD

**Issue by MARCOS30864** [MovTery/ZalithLauncher#196]
### Feature Description / 功能描述

PLAY STORY 

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
Sorry, but I don't have any account to pay Google for registering a developer account.
