### ISSUE TITLE
Pojavlauncer zenith horizon Zink not working

### ISSUE THREAD

**Issue by Ilkerkemec99** [MovTery/ZalithLauncher#197]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

When I select vulkan zink in the game and enter it, it throws me out of the game for no reason and I want to open a shader, please fix this problem.

### Log File / 日志文件

content://net.kdt.pojavlaunch.scoped.gamefolder.zh/document/%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fnet.kdt.pojavlaunch.zh%2Ffiles%2Flatestlog.txt

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.6

### Selected Renderer / 选择的渲染器

Vulkan Zink

### Device Information / 设备信息

Redmi note 12 pro 5g android 14

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Ilkerkemec99** [comment]
> Bazı telefonlar mesa24.x zink renderer'ı desteklemez https://docs.mesa3d.org/drivers/zink.html

Peki hiçbir çözümü yokmu

**Comment by gumen2258** [comment]
你的设备不支持

**Comment by Ilkerkemec99** [comment]
> > > Bazı evlerde mesa24.x zink renderer'ı destekliyorz https://docs.mesa3d.org/drivers/zink.html
> > 
> > 
> > Peki hiçbir çözümü yokmu
> 
> 更换为更低版本的mesa zink或更换为virgl

Is there no solution?

**Comment by ilkerpro78** [comment]
> > > > > Bazı evlerde mesa24.x zink renderer'ı vardırz https://docs.mesa3d.org/drivers/zink.html
> > > > 
> > > > 
> > > > Peki hiçbir çözümü yokmu
> > > 
> > > 
> > > 更换为更低版本的mesa zink或更换为virgl
> > 
> > 
> > Çözümü yok mu?
> 
> 1. Oluşturucunun gereksinimlerini azaltın (yeniden derlemek için kaynak kodunu değiştirmeniz gerekebilir, bu performansını etkileyebilir)
> 2. Sistemin vulkan sürücüsü yerine başlatıcı tarafından kullanılan vulkan sürücüsünü değiştirin
> 3. Snapdragon işlemci kullanılıyorsa Turnip sürücüsünü kullanın. 
>    Bunlar bildiğim çözümler ve daha fazlasını söyleyemem.

I didn't understand the second item, how is it done?
