### ISSUE TITLE
Red Screen (1.21.3)

### ISSUE THREAD

**Issue by guilermt** [MovTery/ZalithLauncher#199]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

the screen turns red when selecting the "Holy" renderer, this only happens in the latest versions such as 1.21.3 of Minecraft

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17511947/latestlog.txt)

### Screenshots or Videos / 截图或视频

![Screenshot_2024-10-24-16-37-43-174_com movtery zalithlauncher](https://github.com/user-attachments/assets/9c70853e-93ef-4337-80f8-5567f50bc634)

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.6

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

Poco X5 Pro, Android 14, arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Dorian12192** [comment]
The same thing happens to me

**Comment by MovTery** [comment]
For versions 1.21.2 and above, please use the LTW renderer.
