### ISSUE TITLE
Pls add ffmpeg and mp3 encorder to render reply mod and record simple voicechat

### ISSUE THREAD

**Issue by OverScarf** [MovTery/ZalithLauncher#200]
### Feature Description / 功能描述

i am using reply mod and simple voice if you add mp3 encoder and ffmpeg so i can reply replays and record simple voicechat

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by Dorian12192** [comment]
Pls Monterrey if you do it we would really appreciate it!
