### ISSUE TITLE
Font name

### ISSUE THREAD

**Issue by Ambientfish** [MovTery/ZalithLauncher#206]
Just want to know the font used in app screenshots
I already tried to identify that font, but i only found the "Antipasto" font family [Screenshot_Launcher_Dark_EN_US.jpg](https://github.com/user-attachments/assets/f14edf99-9bdc-4d96-a3df-82c190d658d7)

It's such a good idea to bring life to the launcher with that font.

**Comment by MovTery** [comment]
https://www.coloros.com/article/A00000050/

**Comment by Ambientfish** [comment]
Sorry for the disturb, but that one is what i need the most![d484afd34e8d82ddd217f62666b9fd3c~2.jpg](https://github.com/user-attachments/assets/21125080-0854-4093-adfa-cb56935a1477)
