### ISSUE TITLE
Bug Install neoforge version 1.21.1

### ISSUE THREAD

**Issue by You-know-123** [MovTery/ZalithLauncher#207]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

Hello I found this bug when I installed neoforge version 1.21.1 it will cause an error I don't know what caused the error so please fix it soon

### Log File / 日志文件

This is not a crash so can't get the log file

### Screenshots or Videos / 截图或视频

![Screenshot_20241029-194823](https://github.com/user-attachments/assets/2677be8a-5ecf-4bd4-a9f0-bc640643a0d2)

### Reproduction Steps / 复现步骤

```markdown
1.Open Zalith Launcher
2.Install neoforge version 1.21.1
3.And that would be an error
```

### Android Version / Android 版本

11

### App Version / 应用版本

1.3.6.2

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

Infinix Hot11s, Android 11, arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
Please try installing with JRE 8.

**Comment by You-know-123** [comment]
I have used jre 8

**Comment by You-know-123** [comment]
Hey @MovTery Please fix it
