### ISSUE TITLE
BUG CURSOR MOUSE || 

### ISSUE THREAD

**Issue by Sall4455** [MovTery/ZalithLauncher#208]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

bug mouse pliss Fix

### Log File / 日志文件

Bug mouse plisss Fix

### Screenshots or Videos / 截图或视频

Bug mouse hehe

### Reproduction Steps / 复现步骤

```markdown
BUG CURSOR MOUSE 
BUG CUROSOR
```

### Android Version / Android 版本

15

### App Version / 应用版本

1.3.6.2

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

Oppo reno7 Z 5G

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Dorian12192** [comment]
No entendemos tu problema, necesitamos más información sobre eso

**Comment by Dorian12192** [comment]
We don't understand your problem, we need more information
