### ISSUE TITLE
Can't see mod in the main menu of minecraft

### ISSUE THREAD

**Issue by JohnreyMartes14** [MovTery/ZalithLauncher#211]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

i can't see mods in main menu of minecraft and i install some mod from zalith and still can't see any mod button

### Log File / 日志文件

non

### Screenshots or Videos / 截图或视频

![Screenshot_2024-10-31-21-26-01-224_com movtery zalithlauncher](https://github.com/user-attachments/assets/9337bd7e-f203-4646-b005-a07d6643ffa3)
![Screenshot_2024-10-31-21-25-56-634_com movtery zalithlauncher](https://github.com/user-attachments/assets/c7088d5a-6384-499c-bf51-3488080086b3)
![Screenshot_2024-10-31-21-25-11-154_com movtery zalithlauncher](https://github.com/user-attachments/assets/8f5c66bf-a6b9-4952-a67d-47c199bd18d2)

### Reproduction Steps / 复现步骤

```markdown
I don't know what to say here
```

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.6.2

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

Poco F5

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
https://modrinth.com/mod/modmenu
