### ISSUE TITLE
Delete Control Problem

### ISSUE THREAD

**Issue by ThatOneSheep** [MovTery/ZalithLauncher#220]
### Issue Type / 问题类型

Application Issue / 应用问题

### Issue Description / 问题描述

When I delete a control, it just immediately crashed my game but at least it actually deleted it.

### Log File / 日志文件

[latestcrash.zip](https://github.com/user-attachments/files/17686398/latestcrash.zip)

### Screenshots or Videos / 截图或视频

https://github.com/user-attachments/assets/9b010dd0-9973-47a7-9bc2-1a55f57db688

### Reproduction Steps / 复现步骤

```markdown
1. Go to Manage Control Layouts
2. Tap a control
3. Press the delete button
```

### Android Version / Android 版本

10

### App Version / 应用版本

1.3.6.4

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

Huawei P30 Lite, Android 10, arm64-v8a

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
Please try this fixed build version.

https://github.com/MovTery/ZalithLauncher/actions/runs/11757150645
