### ISSUE TITLE
ADD FFMPEG TO RENDER REPLAY MOD

### ISSUE THREAD

**Issue by GTG921** [MovTery/ZalithLauncher#231]
### Feature Description / 功能描述

I WAS USING REPLAY MOD.I WANT FFMPEG SUPPORT TO RENDER IT.KINDLY GIVE FFMPEG PLUGIN FOR ZALITH LAUNCHER OR MAKE LAUNCHER SUPPORT IT

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
https://github.com/PojavLauncherTeam/FFmpegPlugin

**Comment by GTG921** [comment]
Does it work with this launcher
