### ISSUE TITLE
Return to the instance system

### ISSUE THREAD

**Issue by Kauannz7** [MovTery/ZalithLauncher#266]
### Feature Description / 功能描述

I think a large part of the community did not like the new version management system. I myself am using the old version 1.3.6.5 at the moment.

### Additional Information / 其他信息

![Screenshot_20241120_102055_Zalith Launcher](https://github.com/user-attachments/assets/68a5df7e-4dae-4524-8cf9-bafe86cfd3de)

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by ZenZenXDz** [comment]
Simply the worst update ever. May I ask whats the reason for removing the instance system?
