### ISSUE TITLE
Controller Bug

### ISSUE THREAD

**Issue by Pityciuu** [MovTery/ZalithLauncher#270]
### Issue Type / 问题类型

Launcher Issue / 启动器问题

### Issue Description / 问题描述

When I edit my default controller, save it, and load it, the settings always reset to the middle, even though I moved the settings buttons to other positions.

### Log File / 日志文件

no log

### Screenshots or Videos / 截图或视频

https://github.com/user-attachments/assets/496a4f14-250d-4b58-91fb-04da7fe2ec3d

### Reproduction Steps / 复现步骤

```markdown
1. Open Zalith Launcher 
2. Edit the current/default controller layout 
3. Configure the current layout controller 
4. Save the layout 
5. open the launcher or re-edit the controller 
6. the settings buttons are always at the middle
```

### Android Version / Android 版本

13

### App Version / 应用版本

1.3.7.4

### Selected Renderer / 选择的渲染器

GL4ES

### Device Information / 设备信息

Infinix Smart 8, andriod 13, arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
That doesn't belong to the control layout; that thing is the game menu floating window.

**Comment by Pityciuu** [comment]
so it'll be there whenever you edit the controller? i just wanted to put that on other position but it doesn't let me

**Comment by MovTery** [comment]
It can be freely dragged by the user, and you can change its default position in the settings (Settings - Game Settings - Game Menu - Initial Position).

**Comment by Pityciuu** [comment]
thanks and sorry I'm just new to the ui thanks again
