### ISSUE TITLE
Add HolyGL4es Renderer Back 

### ISSUE THREAD

**Issue by VinBastard** [MovTery/ZalithLauncher#297]
### Feature Description / 功能描述

Renderer GL4ES Lag In My Phone

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
This is exactly the same thing, I just changed it back to the correct name.
