### ISSUE TITLE
Bug 1.20.6+ Version on 32BIT Devices

### ISSUE THREAD

**Issue by FathirY** [MovTery/ZalithLauncher#299]
### Issue Type / 问题类型

Launcher Issue / 启动器问题

### Issue Description / 问题描述

hello Zalith Launcher developer, there is a bug in your launcher system which is in version 1.20.6+ for 32bit devices it doesn't support that version, for versions below it is still fine because it uses Java 17, if Java 21 there will be a bug on 32bit devices

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17957957/latestlog.txt)

### Screenshots or Videos / 截图或视频

No Screenshot

### Reproduction Steps / 复现步骤

```markdown
i don't know
```

### Android Version / Android 版本

10

### App Version / 应用版本

1.3.7.7

### Selected Renderer / 选择的渲染器

LTW

### Device Information / 设备信息

Samsung A6+,Android 10,arm32

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by FathirY** [comment]
> Try disabling sodium. The log shows that you are using gl4es

Not work

**Comment by FathirY** [comment]
> > > Try disabling sodium. The log shows that you are using gl4es
> > 
> > 
> > Not work
> 
> Try playing vanilla version to determine if it's mods' problem

![Screenshot_20241130-213441_Zalith Launcher](https://github.com/user-attachments/assets/b2f96ee4-1832-49db-9559-ec3483e37c62)

Like this bro my bug on 32bit, check pojav launcher playstore update

**Comment by Vera-Firefly** [comment]
Reference(https://github.com/Vera-Firefly/Pojav-Glow-Worm/issues/281)
